DEBUG: tests/libex29_tests.c:70:main 
--------Running: ./tests/libex29_tests
DEBUG: tests/libex29_tests.c:62:all_tests 
--------test_dlopen---------
DEBUG: tests/libex29_tests.c:63:all_tests 
--------test_functions---------
DEBUG: tests/libex29_tests.c:64:all_tests 
--------test_failures---------
[ERROR] (tests/libex29_tests.c:14:check_function errno: None) Function fail_on_purpose returned: -1 for data: Hello there
[ERROR] (tests/libex29_tests.c:45:test_failures errno: None) fail_on_purpose should fail
